config/routes.rb
OnlineSchool::Application.routes.draw do

  root :to => 'topics#index'

  ##### DEVISE #####

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", passwords: "passwords"}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'sessions#destroy', as: :logout
  end

  ##### RESOURCES #####

  resources :topics 
  resources :tracks
  resources :lessons
  resources :progresses

  resources :comments
  get '/comments/:id/upvote', to: "comments#upvote", as: "comment_upvote"

  get '/announcements/hide', to: 'announcements#hide', as: "hide_announcements"
  resources :announcements

  
  resources :amas
  resources :charges, only: ["create", "new"]
  get '/edit_subscription', to: "charges#edit", as: "edit_charge"
  post '/update_subscription', to: "charges#update", as: "update_charge"
  get '/cancel_subscription', to: 'charges#destroy', as: "destroy_charge"

  get '/auth/facebook/callback', :to => 'auths#facebook_create'
  post '/codes/update', to: 'codes#update', as: "update_code"
  get '/biweeklies', to: "amas#biweeklies", as: 'biweeklies'

  get '/privacy', to: 'home#privacy_policy', as: 'privacy'
  get '/terms', to: 'home#terms', as: 'terms'

  ##### OLD #####
  resources :events
  resources :users, only: ["update", "destroy"]
  get '/users/settings/edit', to: "users#edit", as: "edit_user"
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  
  def self.today
  	where("created_at > (?)", Time.now - 24.hours).where(archived: nil).select {|n| (n.created_at + 7.hours).to_date === (Time.now.utc + 7.hours).to_date}
  end

  def self.date_today
  	(Time.now.utc - 7.hours).strftime("%B %-d, %Y")
  end

  def self.archived_grouped_and_ordered_by_date
  	Announcement.order('created_at desc').where(archived: true).group_by(&:date)
  end

  def date
  	(created_at.utc - 7.hours).strftime("%B %-d, %Y")
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_filter :authenticate_user!
  include ApplicationHelper
  
  def index
  	@announcements = Announcement.archived_grouped_and_ordered_by_date
  end

  def destroy
  	@announcement = Announcement.find(params[:id]).destroy
  	redirect_to root_path
  end

  def create
  	Announcement.create params[:announcement]
  	redirect_to root_path
  end

  def hide
  	Announcement.today.map {|n| n.update_attributes archived: true}
  	redirect_to root_path
  end
end

app/views/announcements/_side_interface.html.erb
<div class="announcements">
  <% if !Announcement.today.empty? %>
    <p class="announcements-header">
      ANNOUNCEMENTS
    </p>

    <p class="announcement-date">
      Posted <%= Announcement.date_today %>
    </p>

    <% @announcements.each do |an| %>
      <div class="announcement">
        <div class="bullet"></div>
        <div class="announcement-body">
          <%= an.body %>
        </div>
      </div>
      <% if @user.role == "admin" %>
        <div class="announcement-actions">
          <%= link_to announcement_path(an), :class => "an-action red-text", method: "delete" do %>
            DELETE
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <% if @user.role == "admin" %>
    <div class="announcement-actions bottom">
      <%= link_to announcements_path, :class => "an-action blue-text" do %>
        ARCHIVE
      <% end %>
      <%= link_to hide_announcements_path, :class => "an-action" do %>
        HIDE
      <% end %>
    </div>
    <%= form_for Announcement.new, id: "payment-form" do |f| %>
      <div class="form-row">
        <%= f.text_field :body, :class => "payment-input" %>
      </div>
      <button type="submit" class="checkout">POST</button>
    <% end %> 
  <% end %>
</div>

app/views/announcements/index.html.erb
<div class="top-section">
  <div class="row">
    <div class="top-column-main">
      <h1 class="no-letter-spacing">Announcements</h1>
    </div><!-- column main -->
  </div><!-- row -->
</div>


<div class="column-main">
	<div class="announcements-container">
		<% @announcements.each do |date, group| %>
		  <div class="announcement-group">
		  	<div class="announcement-date-header">
		  		<%= date %>
		  	</div>
		  	<% group.each do |an| %>
			  	<div class="announcement">
				    <div class="bullet"></div>
				    <div class="announcement-body">
				      <%= an.body %>
				    </div>
			    </div>
			 <% end %>
		  </div>
		<% end %>	
	</div>
</div>