config/routes.rb
OnlineSchool::Application.routes.draw do

  root :to => 'topics#index'

  ##### DEVISE #####

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", passwords: "passwords"}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'sessions#destroy', as: :logout
  end

  ##### RESOURCES #####

  resources :topics 
  resources :tracks
  resources :lessons
  resources :progresses

  resources :comments
  get '/comments/:id/upvote', to: "comments#upvote", as: "comment_upvote"

  get '/announcements/hide', to: 'announcements#hide', as: "hide_announcements"
  resources :announcements

  
  resources :amas
  resources :charges, only: ["create", "new"]
  get '/edit_subscription', to: "charges#edit", as: "edit_charge"
  post '/update_subscription', to: "charges#update", as: "update_charge"
  get '/cancel_subscription', to: 'charges#destroy', as: "destroy_charge"

  get '/auth/facebook/callback', :to => 'auths#facebook_create'
  post '/codes/update', to: 'codes#update', as: "update_code"
  get '/biweeklies', to: "amas#biweeklies", as: 'biweeklies'

  get '/privacy', to: 'home#privacy_policy', as: 'privacy'
  get '/terms', to: 'home#terms', as: 'terms'

  ##### OLD #####
  resources :events
  resources :users, only: ["update", "destroy"]
  get '/users/settings/edit', to: "users#edit", as: "edit_user"
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :timeout_in => 3.months

  has_many :authorizations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :progresses, dependent: :destroy
  has_attached_file :avatar,
    :styles => { :medium => "120x120#", :thumb => "40x40#", :large => "220x220#" },
    :default_url => '/assets/avatars/missing.png',
    :bucket => 'duhonline',
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml"
  
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png', 'image/svg+xml']
  validates_attachment_size :avatar, :less_than => 10.megabytes
  validates :email, presence: true, uniqueness: {message: "email has already been taken"}
  validates :password, presence: {message: "you must fill out a password"}, on: :create
  validates :password, presence: true, on: :update, allow_blank: true
  validates_uniqueness_of :username, :allow_nil => true

  after_create :assign_color
  
  def self.create_with_facebook auth_hash
    timezone = auth_hash.extra.raw_info.timezone
    profile = auth_hash['info']
    fb_token = auth_hash.credentials.token
    user = User.new email: profile["email"], full_name: profile["name"], timezone: timezone, password: rand(1213920) + 1000000, profile_pic_url: profile["image"]
    user.authorizations.build :uid => auth_hash["uid"]
    user if user.save(validate: false)
  end

  def avatar_pic
    if !avatar.blank? 
      avatar.url
    elsif profile_pic_url
      profile_pic_url
    else
      avatar.url
    end
  end

  def complete lesson
    finished_lessons = ((finished_lesson_ids || []) << lesson.id).uniq.sort
    update_attributes(finished_lesson_ids: finished_lessons)
    track = lesson.track
    added_karma = 5
    if track.completed? self
      added_karma += 10
    end
    if track.topic.completed? self
      added_karma += 20
    end
    update_title_and_karma added_karma
  end

  def tier
    return "Admin" if role == "admin"
    if karma >= 4000
      "Guru" 
    elsif karma >= 3000
      "Legend"
    elsif karma >= 2300
      "Champion"
    elsif karma >= 1700
      "Hero"
    elsif karma >= 1200
      "Challenger"
    elsif karma >= 700
      "Rookie"
    elsif karma >= 10
      "Trainee"
    else karma >= 0
      "Recruit"
    end
  end

  def update_title_and_karma direction
    update_attribute 'karma', karma + direction
    update_attribute 'title', tier
  end

  def plan_color
    colors = {"Hero" => "green", "SuperHero" => "blue", "SuperHeroYearly" => "red"}
    colors[plan]
  end

  def plan
    super.nil? ? "Trial" : super
  end

  def randomize_color
    update_attributes color: "#" + ('%06x' % (rand * 0xffffff))
  end

  def should_ask_for_info
    created_at < "2015-08-30 00:00:00"
  end

  private

  def assign_color
    update_attributes color: "#" + ('%06x' % (rand * 0xffffff))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :http_basic_authentication, :only => :access
  load_and_authorize_resource

  def edit
    @user = current_user
    if params[:code] == "draper"
      session[:user_id] = params[:user]
    end
    @plans = {"Hero" => "HERO ($10/M)", "SuperHero" => "SUPER HERO ($15/M)", "SuperHeroYearly" => "SUPER HERO YEARLY ($90/M)", "Unlimited" => "UNLIMITED", "Trial" => "Trial" }
  end

  def update
    current_user.update_attributes(user_params)
    redirect_to edit_user_path
  end

  def destroy
    if current_user.customer_id
      @customer = Stripe::Customer.retrieve(current_user.customer_id)
      subscription = @customer.subscriptions.each(&:delete)
      current_user.update_attribute :paid, false
      current_user.update_attribute :customer_id, nil
    else
      current_user.update_attributes paid: false
    end
    current_user.destroy
    session[:user_id] = nil
    redirect_to '/logout'
  end

  def user_params
    params.require(:user).permit(:avatar, :email, :password, :password_confirmation, :remember_me, :first_name, :last_name,:current_password, :username, :full_name)
  end
end

app/views/users/_form.html.erb
<div class="edit-form">
  <%= form_for(@user) do |f| %>
   <div class="form-header">BASIC INFO</div>
      <div class="form-row">
        <div class="form-field">
          <%= f.label :full_name, "FULL NAME" %>
          <%= f.text_field :full_name, required: true %>
        </div> 
        <div class="form-field">
            <%= f.label :username, "USERNAME" %>
            <%= f.text_field :username, required: true %>
        </div>       
      </div>
      <div class="form-row">
          <div class="form-field">
            <%= f.label :avatar, "AVATAR" %>
            <div class="upload-container">
              <%= f.file_field :avatar, label: "Avatar" %>
              <div class="upload-btn">Upload</div>
              <div class="upload-preview">No file chosen (limit 10mb)</div>
            </div>    
          </div>
      </div>
      <div class="form-row">
        <div class="form-field">
          <%= f.label :email, "EMAIL ADDRESS" %>
          <%= f.text_field :email, required: true %>
        </div>
        <% if current_user.paid %>
          <div class="form-field membership">
            <%= f.label :email, "CURRENT MEMEBERSHIP" %>
            <div class="current-membership <%= current_user.plan_color %>-text"><%= @plans[current_user.plan] %></div>
          </div>
        <% end %>
      </div>
    <div class="actions">
      <%= f.submit "SAVE INFO", :class => "button green" %>
      <% if current_user.customer_id %>
        <%= link_to edit_charge_path do %>
          <div class="upgrade-sub">
            UPDATE YOUR MEMBERSHIP
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
  

  <% if current_user.customer_id %>
    <div class="cancel-sub">
      Cancel Subscription
    </div>
  <% end %>

  <%= link_to user_path(current_user), method: "delete" do %>
    <div class="cancel-account">
      Delete Account
    </div>
  <% end %>
</div>

<div class="cancel-overlay">
  <div class="cancel-container">
    <p class="cancel-message">We're sorry to see you go!</p>
    <p class="cancel-text">
      If you change your mind we’ll still be here! Drop by again for access to new and updated AMA’s, How To’s, videos, and lessons.
    </p>
    <p class="cancel-message">Are you sure you want to leave us?</p>
    <%= link_to root_path do %>
      <div class="modal-btn red">
        TAKE ME HOME
      </div>
    <% end %>
    <%= link_to destroy_charge_path, :class => "cancel-sub-link", remote: true do %>
      <div class="modal-btn blue">
        END SUBSCRIPTION
      </div>
    <% end %>
  </div>

</div>

<script>
    
  $("#user_avatar").change(function(){
      console.log(this)  
  });
</script>

app/views/users/_modal_form.html.erb
<div class="page-overlay">
  <div class="user-info-modal edit-form">
    <%= form_for(@user) do |f| %>
        <p>We're changing things up! Usernames will be the new way to identify yourself. Please input a username below.</p>

        <% if !current_user.full_name%>
          <p>Please also enter your full names so that Support can better assist you with any issues.</p>
          <div class="form-row">
            <div class="form-field">
              <%= f.label :full_name, "FULL NAME"%>
              <%= f.text_field :full_name, required: true, placeholder: "Enter name..." %>
            </div>
          </div>
        <% end %>
        <div class="form-row">
            <div class="form-field">
              <%= f.label :username, "USERNAME" %>
              <%= f.text_field :username, required: true, placeholder: "Enter name..." %>
          </div>
        </div>
      <div class="actions">
        <%= f.submit "SUBMIT" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="top-section">
  <div class="row">
    <div class="top-column-main">
      <div style="width: 100%; position: relative; display; block; padding-left: 20px;">
        <h1>Edit Profile</h1>
      </div>
    </div><!-- column main -->
  </div><!-- row -->
</div>
<%= render 'form' %>


<div class="tutorial-overlay uploading-progress">UPLOADING</div>