config/routes.rb
OnlineSchool::Application.routes.draw do

  root :to => 'topics#index'

  ##### DEVISE #####

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", passwords: "passwords"}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'sessions#destroy', as: :logout
  end

  ##### RESOURCES #####

  resources :topics 
  resources :tracks
  resources :lessons
  resources :progresses

  resources :comments
  get '/comments/:id/upvote', to: "comments#upvote", as: "comment_upvote"

  get '/announcements/hide', to: 'announcements#hide', as: "hide_announcements"
  resources :announcements

  
  resources :amas
  resources :charges, only: ["create", "new"]
  get '/edit_subscription', to: "charges#edit", as: "edit_charge"
  post '/update_subscription', to: "charges#update", as: "update_charge"
  get '/cancel_subscription', to: 'charges#destroy', as: "destroy_charge"

  get '/auth/facebook/callback', :to => 'auths#facebook_create'
  post '/codes/update', to: 'codes#update', as: "update_code"
  get '/biweeklies', to: "amas#biweeklies", as: 'biweeklies'

  get '/privacy', to: 'home#privacy_policy', as: 'privacy'
  get '/terms', to: 'home#terms', as: 'terms'

  ##### OLD #####
  resources :events
  resources :users, only: ["update", "destroy"]
  get '/users/settings/edit', to: "users#edit", as: "edit_user"
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	belongs_to :track
	has_many :comments
	include Extensions::Progressable

	def icon color=nil
		"icons/#{lesson_type}#{color}.svg"
	end

	def slug_name
		description[0..30]
	end

	# number should be obtained from order attribute
	def full_info number 
		short_text = description.split("<br>")[0][0..59]
		short_text = short_text + "..." if short_text.length == 60
		"#{number}. #{short_text}"
	end

	# use linked list structure, store next lesson_id on each lesson
	def next_lesson
		lesson_ids = track.ordered_lessons.map(&:id)
		next_lesson_id = lesson_ids[lesson_ids.index(id) + 1]
		if next_lesson_id
			Lesson.find next_lesson_id
		else
			next_track = track.topic.tracks.where(order: track.order + 1).first
			if next_track
				next_track.ordered_lessons.first
			else
				track.topic
			end
		end
	end

	def self.description_for lesson_type
		if lesson_type == "watch"
			"These are videos clips taken from actual Draper Univerisity lectures. You can learn about entrepreneurship directly from founders, VCs, execs, lawyers, and more.
			<br><br>We’ve cut them up into short, easy clips for you. If you’d like to access the full lectures you’ll need to upgrade to a Superhero Membership."
		elsif lesson_type == "challenge"
			"Learn by doing”. These are a list of activities that we’ve come up with to help you practice your entrepreneurial skills. Many of these are again, actual activities that we have students do at Draper Univeristy, designed to push you outside of your comfort zone.
			<br><br>Absolutely feel free to post your progress or results and share with students so we can give you feedback!"
		elsif lesson_type == "reading"
			"We’ve pulled together a collection of books and articles for you to supplement your learning. These are the same recommendations we give to students here at DU, we hope you find them just as helpful!"
		elsif lesson_type == "discussion"
			"We’ve come up with some discussion questions and topics to help you start thinking in the right direction about startups.
			<br><br>Share your ideas and thoughts with other students. Keep an eye out for Draper U Alumni, mentors, and staff! We’ll come on regularly to give feedback, and share our own insights."
		else
			"Starting a company is hard enough on your own, everyone needs a little help. These are tools and servies already built by other entrepreneurs we think would help you get closer to your goals.
			<br><br>We’ve tried to mostly find free to use tools, but some software may require a purchase. "
		end
	end

	def completed? user
		return false if !user || !user.finished_lesson_ids
		user.finished_lesson_ids.bsearch {|lesson_id| id - lesson_id }
	end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  include ApplicationHelper
  before_filter :only_admins_allowed, except: "show"
  
  def show
    @lesson = Lesson.find params[:id]
    @track = @lesson.track
    @topic = @track.topic
    @user = current_user
    redirect_to "/users/sign_up?resource_id=#{@lesson.id}&resource_type=lesson" and return if !current_user
    redirect_to new_charge_path(lesson_id: @lesson.id) and return if !current_user.paid	&& !@topic.free 

  	@tracks = @topic.tracks
    if @lesson.discussion
    	@comment = Comment.new lesson_id: @lesson.id
      @comments = @lesson.comments.includes(:user)
      @sort = "date"
      if params["sort"] == "top"      
        @comments = @comments.sort_by {|c| c.get_upvotes.size}.reverse
        @sort = "top"
      end
    end
  
    @user = current_user
    @participants = @lesson.participants
    Progress.where(user_id: @user.id, model_type: "lesson", model_id: @lesson.id, percent_complete: 0).first_or_create
  end

  def edit
    @lesson = Lesson.find params[:id]
  end

  def update
    @lesson = Lesson.find params[:id]
    params[:lesson][:lesson_type] = params[:lesson][:lesson_type].downcase.strip
    @lesson.update_attributes lesson_params
    redirect_to lesson_path(@lesson)
  end

  def new
    @lesson = Lesson.new
  end

  def create
    params[:lesson][:lesson_type] = params[:lesson][:lesson_type].downcase.strip
    track = Track.find_by_name params[:chapter].upcase.strip
    lesson = Lesson.create params[:lesson]
    lesson.update_attributes track_id: track.id
    redirect_to lesson_path(lesson)
  end

  private

  def only_admins_allowed
    if current_user.role != "admin"
      redirect_to root_path and return
    end
  end

  def lesson_params
    params.require(:lesson).permit(:lesson_type, :video, :started, :finished, :video_uid, :video_title, :video_author, :body, :discussion, :description, :track_id, :order, :video_length, :slug)
  end

end

app/views/lessons/edit.html.erb
<div class="top-section">
  <div class="row">
    <div class="top-column-main">
      <h1 class="no-letter-spacing">ADMIN SHIT</h1>
    </div><!-- column main -->
  </div><!-- row -->
</div>

<div class="column-main admin">
  <div class="admin-edit">
	<%= form_for @lesson do |f| %>
		<div class="form-section">
			<p class="form-title">
				TOP LEVEL ID SHIT
			</p>
			<div class="form-row">
				<div class="row-left">
					<div class="field-label">
						Lesson type
					</div>
					<%= f.text_field :lesson_type, :class => "form-field", placeholder: "Lesson Type" %>	
				</div>
				<div class="row-right">
				</div>
			</div>
		</div>

		<div class="form-section">
			<p class="form-title">
				LESSON SHIT	
			</p>
			<div class="form-row">
				<div class="row-left">
					<div class="field-label">
						MAIN TEXT (will be side text for videos)
					</div>
					<%= f.text_area :body, :class => "form-field lesson-body", placeholder: "Body (accepts html)" %>
					<div class="field-label">
						LESSON SECTION ORDER
					</div>
					<%= f.text_field :order, :class => "form-field", placeholder: "Order" %>

					<div class="form-field form-switch <%= 'on' if @lesson.discussion %> discussion">
						Discussion
					</div>

					<div class="form-field form-switch <%= 'on' if @lesson.video %> video">
						Video
					</div>

					<%= f.hidden_field :discussion, value: @lesson.discussion %>
					<%= f.hidden_field :video, value: @lesson.video %>

					<%= f.submit "SUBMIT SHIT", :class => "submit-lesson form-field button green" %>
				</div>
				<div class="row-right">
					<div class="field-label">
						VIMEO ID
					</div>
					<%= f.text_field :video_uid, :class => "form-field", placeholder: "Vimeo ID" %>
					<div class="field-label">
						VIDEO TITLE
					</div>
					<%= f.text_field :video_title, :class => "form-field", placeholder: "Video Title" %>
					<div class="field-label">
						VIDEO SPEAKER
					</div>
					<%= f.text_field :video_author, :class => "form-field", placeholder: "Order" %>	
					<div class="field-label">
						SIDE TEXT
					</div>
					<%= f.text_field :description, :class => "form-field", placeholder: "Description" %>	
				</div>
			</div>
		</div>
	<% end %>
  </div>
</div>

<%= content_for :column_right do %>
  <div class="padding"></div>  
  <div class="welcome-container">
  	<%= link_to new_lesson_path do %>
	    <div class="new-lesson-btn">
	    	New Lesson
	    </div>
	<% end %>
	</div>
  </div>
<% end %>

app/views/lessons/new.html.erb
<div class="top-section">
  <div class="row">
    <div class="top-column-main">
      <h1 class="no-letter-spacing">ADMIN SHIT</h1>
    </div><!-- column main -->
  </div><!-- row -->
</div>

<div class="column-main admin">
  <div class="admin-edit">
	<%= form_for @lesson do |f| %>
		<div class="form-section">
			<p class="form-title">
				TOP LEVEL ID SHIT
			</p>
			<div class="form-row">
				<div class="row-left">
					<div class="field-label">
						Lesson type 
					</div>
					<%= f.text_field :lesson_type, :class => "form-field", placeholder: "Lesson Type" %>	
				</div>
				<div class="row-right">
					<div class="field-label">
							Chapter (upper/lower case doesn't matter)
						</div>
						<%= text_field_tag :chapter, nil, :class => "form-field", placeholder: "Chapter" %>	
					</div>
			</div>
		</div>

		<div class="form-section">
			<p class="form-title">
				LESSON SHIT	
			</p>
			<div class="form-row">
				<div class="row-left">
					<div class="field-label">
						MAIN TEXT (will be side text for videos)
					</div>
					<%= f.text_area :body, :class => "form-field lesson-body", placeholder: "Body (accepts html)" %>
					<div class="field-label">
						LESSON SECTION ORDER
					</div>
					<%= f.text_field :order, :class => "form-field", placeholder: "Order" %>

					<div class="form-field form-switch <%= 'on' if @lesson.discussion %> discussion">
						Discussion
					</div>

					<div class="form-field form-switch <%= 'on' if @lesson.video %> video">
						Video
					</div>

					<%= f.hidden_field :discussion, value: @lesson.discussion %>
					<%= f.hidden_field :video, value: @lesson.video %>

					<%= f.submit "Submit Shit", :class => "submit-lesson form-field button green" %>
				</div>
				<div class="row-right">
					<div class="field-label">
						VIMEO ID
					</div>
					<%= f.text_field :video_uid, :class => "form-field", placeholder: "Vimeo ID" %>
					<div class="field-label">
						VIDEO TITLE
					</div>
					<%= f.text_field :video_title, :class => "form-field", placeholder: "Video Title" %>
					<div class="field-label">
						VIDEO SPEAKER
					</div>
					<%= f.text_field :video_author, :class => "form-field", placeholder: "Order" %>	
					<div class="field-label">
						SIDE TEXT (MANDATORY)
					</div>
					<%= f.text_field :description, :class => "form-field", placeholder: "Description" %>	
				</div>
			</div>
		</div>
	<% end %>
  </div>
</div>

app/views/lessons/show.html.erb
<% if @lesson.lesson_type != "tools" %>
  <%= content_for :side_nav do %>
    <div class="lessons-nav">
      <% @tracks.order(:order).each_with_index do |track, i| %>
        <div class="bar-group">
          <div class="bar-header">
            <%= link_to track_path(track) do %>
              Chapter <%= i + 1 %> - <%= track.name.downcase.split.map(&:capitalize)*' ' %>
            <% end %>
          </div>
          <% counter = 0 %>
          <% track.type_sorted_lessons.flatten.each_with_index do |lesson, i| %>
            <% next if !lesson || lesson == "tools" %>
            <% if lesson.class == String %>
              <div class="bar-item type-header">
                <%= image_tag "lesson_type_icons/#{lesson}.svg", :class => "bar-icon" %>
                <p class="bar-text <%= lesson %>"><%= lesson.upcase %></p>
                <div></div>
                <% counter = 0 %>
              </div>
            <% else %>
              <% counter += 1 %>
              <% if lesson.lesson_type != "tools" %>
                <div class="bar-item <%= 'current' if lesson == @lesson %>">
                  <%= link_to lesson_path(lesson) do %>
                    <%= image_tag lesson.status_icon(@user), :class => "bar-circle" %>
                    <p class="bar-text">
                      <%= lesson.full_info counter %>
                    </p>
                    <div></div>  
                  <% end %>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

<div class="top-section <%= @lesson.lesson_type.downcase %>">
  <div class="row">
    <div class="top-column-main">
      <%= link_to track_path(@track) do %>
        <p class="header-back"><< LESSONS</p>
      <% end %>
      <h1 class="no-letter-spacing"><%= @lesson.lesson_type.capitalize.downcase.split(" ").map(&:capitalize).join(" ")  %></h1>

      <% if @lesson.completed?(@user) %>
        <p class="header-info complete-btn completed">COMPLETED</p>
      <% else %>
        <%= form_for Progress.new do |f| %>
          <%= f.hidden_field :model_id, value: @lesson.id %>
          <%= f.submit "COMPLETE & CONTINUE", :class => "header-info complete-btn" %>
        <% end %>
      <% end %>
    </div><!-- column main -->
  </div><!-- row -->
</div>

<div class="column-main">
  <div class="lesson-container">
    <% if @lesson.video %>
      <iframe src="https://player.vimeo.com/video/<%= @lesson.video_uid %>" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> 
    <% end %>

    <% if @lesson.body && @lesson.lesson_type != "watch" %>
      <div class="lesson-body linkify <%= @lesson.lesson_type.downcase %>-body">
        <%= @lesson.body.html_safe %>
      </div>
    <% end %>

    <% if @lesson.discussion %>
      <%= form_for @comment, remote: true, html: {:class => "main-comment new_comment"} do |f| %>
        <%= f.text_area :body, :class => "comment-body", placeholder: "Post a response..." %>
        <%= f.hidden_field :lesson_id, value: @lesson.id %>
        <div class="comment-form-bottom">
          <div class="sort-bar">
            <p>Sort by:</p>
            <%= link_to lesson_path(id: @lesson.id, sort: "new") do %>
              <p class="<%= 'active' if @sort == "date" %> sort-item">New</p>
            <% end %>
            <%= link_to lesson_path(id: @lesson.id, sort: "top") do %>
              <p class="<%= 'active' if @sort == "top" %> sort-item">Top</p>
            <% end %>
          </div>
          <div class="submit-container">
            <%= f.submit "Submit", :class => "submit-comment button green" %>
            <p class="submit-status green-text">SUBMITTING...</p> 
          </div>
          
        </div> 
      <% end %>
       <div class="comments">
        <% @comments.each do |comment| %>
          <%= render partial: "comments/comment", locals: {comment: comment, commentable: @lesson} %>
        <% end %>
      </div>
    <% end %>
  </div>
</div><!-- column-main -->
<%= content_for :column_right do %>
  <div class="chat-header">
    <p>INFORMATION</p>
  </div>
  <div class="video-side-info">
    <% if @user.role == "admin" %>
      <%= link_to edit_lesson_path(@lesson) do %>
        <div class="new-lesson-btn">
          Edit Lesson
        </div>
      <% end %>
    <% end %>

    <% if @lesson.video %>
        <p class="video-title">
          <%= @lesson.video_title.upcase %>
        </p>
        <p class="video-author">
          <%= @lesson.video_author %>
        </p>
    <% end %>

    <% if @lesson.lesson_type == "watch" && @lesson.body %>
      <p class="video-body">
        <%= @lesson.body.html_safe %>
      </p>
    <% end %>
  </div>

    <% if @participants.length > 0 %> 
      <div class="participants <%= @lesson.lesson_type.downcase %>">
        <p class="participants-header">
          STUDIED BY:
        </p>
        <div class="participants-list">
          <% @participants[0..10].each do |user| %>
            <%= image_tag user.avatar_pic, :class => "participant" %>
          <% end %>
          <% if @participants.length > 11 %>
            <div class="more-participants participant">
             <%=  @participants.length - 11 %>+
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
<% end %>

<script>
  $('#side-nav').addClass('scrollable')
</script>