config/routes.rb
OnlineSchool::Application.routes.draw do

  root :to => 'topics#index'

  ##### DEVISE #####

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", passwords: "passwords"}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'sessions#destroy', as: :logout
  end

  ##### RESOURCES #####

  resources :topics 
  resources :tracks
  resources :lessons
  resources :progresses

  resources :comments
  get '/comments/:id/upvote', to: "comments#upvote", as: "comment_upvote"

  get '/announcements/hide', to: 'announcements#hide', as: "hide_announcements"
  resources :announcements

  
  resources :amas
  resources :charges, only: ["create", "new"]
  get '/edit_subscription', to: "charges#edit", as: "edit_charge"
  post '/update_subscription', to: "charges#update", as: "update_charge"
  get '/cancel_subscription', to: 'charges#destroy', as: "destroy_charge"

  get '/auth/facebook/callback', :to => 'auths#facebook_create'
  post '/codes/update', to: 'codes#update', as: "update_code"
  get '/biweeklies', to: "amas#biweeklies", as: 'biweeklies'

  get '/privacy', to: 'home#privacy_policy', as: 'privacy'
  get '/terms', to: 'home#terms', as: 'terms'

  ##### OLD #####
  resources :events
  resources :users, only: ["update", "destroy"]
  get '/users/settings/edit', to: "users#edit", as: "edit_user"
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  include ApplicationHelper
  skip_before_filter :ensure_payment


  def new
    @bad_code = params['bad_code'] == "true"
  end

  def create
    #create error catching
    if !current_user.customer_id #find or create customer from stripe
      @customer = Stripe::Customer.create(:description => current_user.full_name, :source => params["stripeToken"])
      current_user.update_attribute :customer_id, @customer.id
    else
      @customer = Stripe::Customer.retrieve(current_user.customer_id)
    end
    @plan = params["plan"] || "Hero" 
    #find or create subscription
    if @customer.subscriptions.count > 0
      @subscription = @customer.subscriptions.first
      @subscription.plan = @plan
      @subscription.save
    else
      begin
        @subscription = @customer.subscriptions.create plan: @plan
      rescue Stripe::InvalidRequestError
        current_user.update_attribute :customer_id, nil
        redirect_to new_charge_path(message: "Invalid Payment Info") and return
      end
    end
    current_user.update_attribute :email, params[:email]
    current_user.update_attribute :plan, @plan
    current_user.update_attribute :paid, true
    UserMailer.payment_confirmation(current_user).deliver if current_user.paid
    
    if params[:lesson_id] !=  ""
      redirect_to lesson_path(params[:lesson_id]) and return
    else
      redirect_to root_path 
    end
  end

  def edit 
  end

  def update
    @customer = Stripe::Customer.retrieve(current_user.customer_id)
    @plan = params["plan"] || "Hero"
    @subscription = @customer.subscriptions.first
    @subscription.plan = @plan
    @subscription.save
    current_user.update_attributes plan: @plan, paid: true
    redirect_to edit_user_path
  end

  def destroy
    if current_user.customer_id
      @customer = Stripe::Customer.retrieve(current_user.customer_id)
      subscription = @customer.subscriptions.each(&:delete)
      current_user.update_attribute :paid, false
      current_user.update_attribute :customer_id, nil
    else
      current_user.update_attributes paid: false
    end
    render json: {message:  "Your subscription has been cancelled."}
  end
end

app/views/charges/create.html.erb
<div class="top-section">
  <div class="row">
    <div class="top-column-main">
      <h1>Thank You!</h1>
    </div><!-- column main -->
  </div><!-- row -->
</div>


<div class="column-main">

</div>

<div class="column-right">
</div>

app/views/charges/edit.html.erb
<div class="top-section">
  <div class="row">
    <div class="top-column-main">
      <h1>Enroll Now</h1>
    </div><!-- column main -->
  </div><!-- row -->
</div>


<div class="column-main">
  <div id="plans">

    <p class="plans-text">
      You’ll need to purchase membership to view our online courses, select one of the memberships below and check out to start your entrepreneurial learning!
    </p>

    <div class="plans-container">
      <div class="plan selected hero" data-plan="Hero">
        <div class="plan-select">
          <%= image_tag "untouched.svg", :class => "plan-icon hidden unselected" %>
          <%= image_tag "done.svg", :class => "plan-icon selected" %>
        </div>
        <div class="plan-info">
          <p class="plan-title green-text">HERO</p>
          <div class="plan-divider"></div>
          <p class="plan-price green-text">$10/month</p>
          <p class="plan-description">Get access to courses, weekly hangouts, and monthly live interviews with Silicon Valley’s best.</p>    
        </div>
      </div>

      <div class="plan superhero" data-plan="SuperHero">
        <div class="plan-select">
          <%= image_tag "untouched.svg", :class => "plan-icon unselected" %>
          <%= image_tag "checkblue.svg", :class => "plan-icon hidden selected" %>
        </div>
        <div class="plan-info">
          <p class="plan-title blue-text">SUPERHERO</p>
          <div class="plan-divider"></div>
          <p class="plan-price blue-text">$15/month</p>
          <p class="plan-description">Same as the Hero Package, but you get access to the entire library of past Draper lectures, interviews, and fireside chats. </p>    
        </div>
      </div>

      <div class="plan superhero-yearly" data-plan="SuperHeroYearly">
        <div class="plan-select">
          <%= image_tag "untouched.svg", :class => "plan-icon unselected" %>
          <%= image_tag "checkred.svg", :class => "plan-icon hidden selected" %>
        </div>
        <div class="plan-info">
          <p class="plan-title red-text">YEARLY</p>
          <div class="plan-divider"></div>
          <p class="plan-price red-text">$90/year</p>
          <p class="plan-description">Get everything in the Superhero, but we’ll give you 6 months free!</p>    
        </div>
      </div>
   </div>
  </div>
</div><!-- column-main -->

<%= content_for :column_right do %>
  <div class="chat-header">
    <p>INFORMATION</p>
  </div>
  <div class="column-body payment">
    <%= form_tag update_charge_path, id: "payment-form" do %>
      <input type="hidden" name="plan" value="Hero" id="plan-input">
      <input type="hidden" name="lesson_id" value="<%= params[:lesson_id] %>">
      <button type="submit" class="checkout">UPDATE MEMBERSHIP</button>
      <p>
        Payment will be prorated over the period of membership you buy:<br><br>
        If you decide to upgrade, we’ll add on any extra charges at the beginning of the next billing cycle. <br><br>
        If you downgrade we’ll credit you for the amount of time you had left.<br><br>
        If you cancel your subscription you will get to keep the access you have already paid for until the end of the final billing cycle.
      </p>
    <% end %> 
  </div>

<% end %>

app/views/charges/new.html.erb
<div class="top-section">
  <div class="row">
    <div class="top-column-main">
      <h1>Enroll Now</h1>
    </div><!-- column main -->
  </div><!-- row -->
</div>


<div class="column-main">
  <div id="plans">

    <p class="plans-text">
      You’ll need to purchase membership to view our online courses, select one of the memberships below and check out to start your entrepreneurial learning!
    </p>

    <div class="plans-container">
      <div class="plan selected hero" data-plan="Hero">
        <div class="plan-select">
          <%= image_tag "untouched.svg", :class => "plan-icon hidden unselected" %>
          <%= image_tag "done.svg", :class => "plan-icon selected" %>
        </div>
        <div class="plan-info">
          <p class="plan-title green-text">HERO</p>
          <div class="plan-divider"></div>
          <p class="plan-price green-text">$10/month</p>
          <p class="plan-description">Get access to courses, weekly hangouts, and monthly live interviews with Silicon Valley’s best.</p>    
        </div>
      </div>

      <div class="plan superhero" data-plan="SuperHero">
        <div class="plan-select">
          <%= image_tag "untouched.svg", :class => "plan-icon unselected" %>
          <%= image_tag "checkblue.svg", :class => "plan-icon hidden selected" %>
        </div>
        <div class="plan-info">
          <p class="plan-title blue-text">SUPERHERO</p>
          <div class="plan-divider"></div>
          <p class="plan-price blue-text">$15/month</p>
          <p class="plan-description">Same as the Hero Package, but you get access to the entire library of past Draper lectures, interviews, and fireside chats. </p>    
        </div>
      </div>

      <div class="plan superhero-yearly" data-plan="SuperHeroYearly">
        <div class="plan-select">
          <%= image_tag "untouched.svg", :class => "plan-icon unselected" %>
          <%= image_tag "checkred.svg", :class => "plan-icon hidden selected" %>
        </div>
        <div class="plan-info">
          <p class="plan-title red-text">YEARLY</p>
          <div class="plan-divider"></div>
          <p class="plan-price red-text">$90/year</p>
          <p class="plan-description">Get everything in the Superhero, but we’ll give you 6 months free!</p>    
        </div>
      </div>
   </div>
  </div>
</div><!-- column-main -->

<%= content_for :column_right do %>
  <div class="chat-header">
    <p>PAYMENT INFO</p>
  </div>

  <div class="column-body payment">
    <%= form_tag '/charges', id: "payment-form" do %>
      <span class="payment-errors"></span>

      <div class="form-row">
        <input type="text" name="full-name" class="payment-input" placeholder="Full Name" required="true"/>
      </div>

      <div class="form-row">
        <input type="text" name="email" class="payment-input" placeholder="Email" required="true"/>
      </div>

      <div class="form-row">
        <input type="text" name="card-number" data-stripe="number" class="payment-input" placeholder="Card Number" required="true"/>
      </div>

      <div class="form-row">
        <input type="text" name="exp-month" data-stripe="exp-month" class="payment-input mini" placeholder="MM" required="true"/>
        <input type="text" name="exp-year" data-stripe="exp-year" class="payment-input mini" placeholder="YY" required="true"/>
        <input type="text" name="cvc" data-stripe="cvc" class="payment-input mini" placeholder="CVC" required="true"/>
      </div>

      <input type="hidden" name="plan" value="Hero" id="plan-input">
      <input type="hidden" name="lesson_id" value="<%= params[:lesson_id] %>">


      <button type="submit" class="checkout">CHECKOUT</button>

      <p class="red-text"><%= params[:message] %></p>
    <% end %> 

    <div class="column-bottom">
      <p class="column-header">ALUMNI ACCESS</p>
      <%= form_tag update_code_path, :class => "code-form" do %>
        <%= text_field_tag :code, nil, :class => "payment-input #{'error' if @bad_code}", placeholder: "Code" %>
        <input type="hidden" name="lesson_id" value="<%= params[:lesson_id] %>">
        <button type="submit" class="checkout code">SUBMIT</button>
      <% end %>
    </div>
  </div>

<% end %>



<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');
  // ...

  $(function($) {
    $('#payment-form').submit(function(event) {
      var $form = $(this);

      // Disable the submit button to prevent repeated clicks
      $form.find('button').prop('disabled', true);

      Stripe.card.createToken($form, stripeResponseHandler);

      // Prevent the form from submitting with the default action
      return false;
    });

    function stripeResponseHandler(status, response) {
      var $form = $('#payment-form');

      if (response.error) {
        // Show the errors on the form
        $form.find('.payment-errors').text(response.error.message);
        $form.find('button').prop('disabled', false);
      } else {
        //response contains id and card, which contains additional card details
        var token = response.id;
        // Insert the token into the form so it gets submitted to the server
        $form.append($('<input type="hidden" name="stripeToken" />').val(token));
        // and submit
        $form.get(0).submit();
      }
    };
  });
</script>